### PR TITLE
Amend #17: Timeout option

### PR DESCRIPTION
**Pull request by ffrank**
Took in PR #17 and made some improvements:
 * stop imposing our own default timeout
 * adhere to global defaults etc.
 * add tests

This also removes some unrelated code changes.

### CODE REVIEW

**Comment by ffrank** [comment]
Pinging @noma4i - this includes your change from PR #17, so I would like to close that in favor of this one. Could you give it a review?

**Comment by noma4i** [comment]
Sure, my PR was old and dirty

**Comment by noma4i** [comment]
Checked your code. Windows default TEMP folder now is **%userprofile%\AppData\Local\Temp** **c:\temp** may not exist at fresh windows instance. We use **$env:TEMP** in powershell templates to get proper path.

**Comment by ffrank** [comment]
Sounds good. If Facter reports this value to the master, I would love to see it used.

It's out of the scope of the timeout feature, however. A new PR (or failing that, an issue) would be most appreciated!

If the implementation looks good to you apart from that, I'll wait for a week or so for another +1, and otherwise merge on the basis of our mutual review :)

**Comment by liamjbennett** [comment]
+1 looks good to me.

**Comment by ffrank** [comment]
Thanks @liamjbennett! Merged.

**Pull request merged**
