### PR TITLE
Prepare for 1.3.0 release

### PR DESCRIPTION
**Pull request by juniorsysadmin**

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
@ffrank Um, the removal of the timeout value is a breaking change, is it not?

**Comment by ffrank** [comment]
You mean #23? That *adds* the `timeout` option, no?

Let's release `1.2.0` before jumping to `2.x`. Let's also not skip `2.0.0`.

**Comment by juniorsysadmin** [comment]
> You mean #23? That adds the timeout option, no?

That looks like the removal of a default value, which is a breaking change, meaning we needed to jump a major release.

> Let's also not skip 2.0.0.

Sorry that was a stuffup, should have been 2.0.0

**Comment by ffrank** [comment]
Ah, I see. The `timeout` parameter does not impose a new behavior unless the user specifies an explicit value. So that's non-breaking. The `exec` never actually passed a `timeout` value before.

Otherwise, this is looking good now. Would you make a `1.2.0` PR as well, or should I?

**Comment by igalic** [comment]
@ffrank yes plz do

**Comment by ffrank** [comment]
Oh, we *were* at `1.2.1` already. Sorry, I got confused since there was no changelog for this latest release.

So, we should step to `1.3.0` right now. @juniorsysadmin will you also tag the commit with `v1.3.0`? That will hopefully trigger a release...

**Comment by ffrank** [comment]
Thanks so much @juniorsysadmin !

**Pull request merged**
