### PR TITLE
Modulesync + removal of proxyAddress variable

### PR DESCRIPTION
**Pull request by juniorsysadmin**
This change:
- Performs a modulesync
- Drops Ruby 1.8.7 TravisCI testing
- Fixes Puppet:Error tests which earlier versions of rspec-puppet were wrongly passing
- Removes the proxyAddress variable

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
This modulesync also drops testing of Ruby 1.8.7.

**Comment by ffrank** [comment]
Thanks, this is quite a handful.

It's a breaking change and requires a major release. I'm fine with that, although we should likely first release the deprecation of `proxyAddress` in #25 in a pointrelease. Thoughts?

I have not looked at the documentation changes in detail, but this seems to cut down on a lot. Some elaboration would be helpful. Ideally, in the form of some prose in the commit message. The current one doesn't do the size of the patch any justice.

**Comment by juniorsysadmin** [comment]
The deprecation of the variable in a point release (I would prefer only that change be done in a specific PR) is the right thing to do. I just think it's more trouble than it's worth.

**Comment by juniorsysadmin** [comment]
Variable deprecation has been done in #27

**Comment by juniorsysadmin** [comment]
Ready for merge

**Comment by juniorsysadmin** [comment]
@ffrank Wait for your squash of #25 or merge?

**Comment by juniorsysadmin** [comment]
@ffrank Merging.

**Comment by ffrank** [comment]
Thanks! Sorry for being out of touch.

**Pull request merged**
