### PR TITLE
Proxy credentials

### PR DESCRIPTION
**Pull request by ffrank**
Takes the changes from #16, rebased to master, and amends some UI changes and documentation changes.

Also, notably, I took this opportunity to deprecate the `proxyAddress` parameter in favor of `proxy_address`.

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
```proxyAddress``` removal has also been done in #26

**Comment by ffrank** [comment]
Rebased after #27 was merged, making this one a little simpler.

I'd like to merge this before releasing `2.0`. A +1 or two would be appreciated.

**Comment by juniorsysadmin** [comment]
@ffrank What is the reasoning behind the use of -securestring ?

**Comment by juniorsysadmin** [comment]
@ffrank I am reasonably okay with this, after a squash :tropical_drink:

**Comment by igalic** [comment]
now that we can do squash ourselves, this doesn't merge anymore :(

**Comment by ffrank** [comment]
Ah right, we are now in the prep phase for a `2.0` release. I need to remove the backwards compatibility (`proxyAddress`) from this, because that is no longer in master.

**Comment by bastelfreak** [comment]
ping @ffrank. I would like to kick out the next release in a few days and want to include this PR.

**Pull request closed without merging**
